apiVersion: apps/v1
kind: Deployment
metadata:
  name: forexservice
  labels:
    app: forexservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forexservice
  template:
    metadata:
      labels:
        app: forexservice
    spec:
      containers:
      - name: forexservice
        image: servicemeshbaoliang.azurecr.io/forexservice
        ports:
        - containerPort: 80