apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: springbootmicroserviceforexservice 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootmicroserviceforexservice 
    spec:
      containers:
        - name: springbootmicroserviceforexservice 
          image: servicemeshbaoliang.azurecr.io/springbootmicroserviceforexservice
          ports:
          - containerPort: 8080