apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: servicemesh 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicemesh 
    spec:
      containers:
        - name: servicemesh 
          image: servicemeshbaoliang.azurecr.io/servicemesh
          ports:
          - containerPort: 80