apiVersion: v1
kind: Service
metadata:
  name: forexservice
  labels:
    app: forexservice
spec:
  selector:
    app: forexservice
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80